// Generates content/today.json:
//   - Word of the day:  pick words[dayOfYear % words.length]
//   - Fact of the day:  pick facts[dayOfYear % facts.length]
//   - News (DE):        first non-wrap-up item from ZDF logo! RSS
//   - News (EN):        first non-"Watch Newsround" item from BBC Newsround RSS
//
// Falls back to the previous today.json's news block if either feed errors,
// so a flaky network won't blank out the kids' news card.
//
// Designed to run in GitHub Actions on Node 20+ (built-in fetch).
// Local run: `node scripts/generate-today.mjs` from the repo root.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const ZDF_LOGO_URL = 'https://www.zdf.de/rss/zdf/kinder/logo';
const BBC_NEWSROUND_URL = 'https://feeds.bbci.co.uk/newsround/rss.xml';

// Items whose title matches any of these are skipped (daily wrap-ups, not
// individual stories). The kids' news card shows one substantive headline.
const ZDF_SKIP = [/^(Montag|Dienstag|Mittwoch|Donnerstag|Freitag|Samstag|Sonntag),/i];
const BBC_SKIP = [/^Watch Newsround/i];

function dayOfYear(date) {
  const start = Date.UTC(date.getUTCFullYear(), 0, 0);
  const diff = date.getTime() - start;
  return Math.floor(diff / 86400000); // 1..366
}

function decodeEntities(s) {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, n) => String.fromCharCode(parseInt(n, 16)));
}

function parseRssItems(xml) {
  const items = [];
  const re = /<item\b[\s\S]*?<\/item>/g;
  let m;
  while ((m = re.exec(xml))) {
    const block = m[0];
    const titleMatch = block.match(/<title>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/);
    const linkMatch = block.match(/<link>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/link>/);
    const title = titleMatch ? decodeEntities(titleMatch[1].trim()) : '';
    const link = linkMatch ? linkMatch[1].trim() : '';
    if (title) items.push({ title, link });
  }
  return items;
}

function pickRealItem(items, skipPatterns) {
  for (const item of items) {
    if (skipPatterns.some((p) => p.test(item.title))) continue;
    return item;
  }
  return items[0] || null;
}

async function fetchHeadline(url, skipPatterns, source) {
  const res = await fetch(url, { headers: { 'User-Agent': 'bearagent-daily/1.0' } });
  if (!res.ok) throw new Error(`${source} HTTP ${res.status}`);
  const xml = await res.text();
  const items = parseRssItems(xml);
  const item = pickRealItem(items, skipPatterns);
  if (!item) throw new Error(`${source} no items`);
  return { headline: item.title, source, url: item.link };
}

function loadJson(relPath) {
  const p = join(ROOT, relPath);
  return JSON.parse(readFileSync(p, 'utf8'));
}

async function main() {
  const today = new Date();
  const dateStr = today.toISOString().slice(0, 10);

  const words = loadJson('content/words.json');
  const facts = loadJson('content/facts.json');
  const doy = dayOfYear(today);

  const word = words[doy % words.length];
  const fact = facts[doy % facts.length];

  // Fallback news from the previous today.json if a feed errors
  let previous = null;
  if (existsSync(join(ROOT, 'content/today.json'))) {
    try { previous = loadJson('content/today.json'); } catch (_) {}
  }

  const news = { de: null, en: null };
  try {
    news.de = await fetchHeadline(ZDF_LOGO_URL, ZDF_SKIP, 'ZDF logo!');
  } catch (err) {
    console.warn('[warn] ZDF logo!:', err.message);
    news.de = (previous && previous.news && previous.news.de) || {
      headline: 'Keine Schlagzeile verfügbar', source: 'ZDF logo!', url: ''
    };
  }
  try {
    news.en = await fetchHeadline(BBC_NEWSROUND_URL, BBC_SKIP, 'BBC Newsround');
  } catch (err) {
    console.warn('[warn] BBC Newsround:', err.message);
    news.en = (previous && previous.news && previous.news.en) || {
      headline: 'No headline available', source: 'BBC Newsround', url: ''
    };
  }

  const out = {
    date: dateStr,
    _note: 'Generated by scripts/generate-today.mjs via .github/workflows/daily-content.yml',
    word,
    fact,
    news
  };

  writeFileSync(join(ROOT, 'content/today.json'), JSON.stringify(out, null, 2) + '\n');
  console.log(`✓ today.json written for ${dateStr}`);
  console.log(`  word: ${word.de.word} / ${word.en.word}`);
  console.log(`  fact: ${fact.de.slice(0, 60)}…`);
  console.log(`  news.de: ${news.de.headline.slice(0, 60)}…`);
  console.log(`  news.en: ${news.en.headline.slice(0, 60)}…`);
}

main().catch((err) => {
  console.error('✗ generate-today failed:', err);
  process.exit(1);
});
